[project]
name = 'Decentralized-Renewable-Energy-Certificate'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certificate-contract]
path = 'contracts/certificate-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.generation-contract]
path = 'contracts/generation-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
